# Generated by Django 5.0.6 on 2024-07-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityAir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('airquality', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='personsalary',
            name='education',
            field=models.CharField(max_length=150),
        ),
    ]
